---
title: "Assignment 1"
author: "Samantha Schloeman, Megan Jones, R "

output: html_document
---

Instructions
------------

Please follow the instructions below to complete your assignment:

1. Open the R markdown template **biostatistics-assignmentTemplate.Rmd** in RStudio
2. Insert the relevant information (i.e., assignment number, names of all students in the group)
3. Save the file as **assnNUMBER-yourLastNames.Rmd** replacing **NUMBER** with the assignment \# and replacing **yourLastNames** with the last names of all individuals in the Group. For example **assn1-SmithJohnson.Rmd**
4. Your answers should consist of the R code used to generate the results and their interpretation
5. Do not use any special symbols such as \%, \#, \$, and \& in your answers
6. Generate an HTML version of the Markdown document by clicking on the **Knit** icon in RStudio
7. ONE PERSON in the group: Email an HTML and Markdown version of your completed assignment to your TA
8. ONE PERSON in the group: Upload the Markdown version of your completed assignment to Turnitin on Blackboard. (Failure to complete this will result in a 10% deduction off your grade.)

### Statement of Author contributions
Please list all questions here and and the specific contribution of the author(s) to answering the question.

Problem 1
---------
### Question 1
```{r}

```


Problem 2

##Question 1
```{r}
d1 <- read.csv(file = "http://faraway.neu.edu/data/assn1_dataset1.csv")
#Ho: The seasonal flu and swine flu affect the same ages
#Ha: The seasonal flu and swine flu do not affect the same ages
```

